CREATE database wheelsOfFortune;

USE `wheelsOfFortune`;

CREATE TABLE `users` (
    id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password varchar(100) NOT NULL
);
Create TABLE `cars` (
    id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type ENUM('BMW', 'mercedes', 'audi', 'volkswagen', 'ford-pickup', 'dodge', 'jeep', 'lexus', 'landrover', 'mini'),
    model VARCHAR(100) NOT NULL,
    image_url VARCHAR(100) NOT NULL,
    price INT NOT NULL,
    color ENUM('zwart', 'wit', 'rood', 'blauw', 'groen', 'geel', 'paars', 'oranje', 'grijs', 'bruin', 'zilver', 'goud', 'roze', 'transparant', 'multicolor'),
    amount INT NOT NULL,
    engine ENUM('diesel', 'benzine', 'elektrisch') NOT NULL,
    horse_power VARCHAR(100) NOT NULL,
    year_of_release int NOT NULL,
    summary TEXT NOT NULL
);

CREATE TABLE `owners` (
    naam VARCHAR(255),
    age INT,
    summary TEXT,
    class VARCHAR(255),
    instagram VARCHAR(255),
    snapchat VARCHAR(255)
);

/* owners */
INSERT INTO `owners` (`naam`, `age`, `summary`, `class`, `instagram`, `snapchat`)
VALUES
('Stefan', 16, 'Er was eens een jongen genaamd Stefan. Hij woonde in een klein dorpje aan de rand van een uitgestrekt bos. Stefan was altijd al gefascineerd geweest door de verhalen die zijn grootvader hem vertelde over de mysterieuze wezens die in het bos leefden.
<br><br>
Op een dag besloot Stefan het bos in te trekken, op zoek naar avontuur. Terwijl hij dieper het bos in wandelde, begon hij te merken dat er iets vreemds aan de hand was. De bomen werden groter en dichter op elkaar, en de geluiden om hem heen begonnen te veranderen. Het leek alsof er een vreemde kracht in het bos was die hem naar binnen trok.
<br><br>
Na een tijdje kwam Stefan aan bij een open plek, waar een prachtige vijver lag. Hij zag een wezen zitten aan de rand van het water. Het was een fee, met vleugels die schitterden als diamanten en een glimlach die de zon liet schijnen.
<br><br>
"Stefan," zei de fee met een zachte stem. "Je hebt moed getoond door hier te komen. Ik heb je hulp nodig. Het bos wordt bedreigd door een duistere kracht en alleen jij kunt het stoppen."
<br><br>
Stefan twijfelde geen moment en beloofde de fee te helpen. Ze gaf hem een magische amulet die hem zou beschermen tegen de duistere krachten van het bos en leidde hem naar een geheime grot. Daar ontmoette Stefan een machtige tovenaar, die hem leerde hoe hij de kracht van de amulet kon gebruiken om de duistere kracht te verslaan.
<br><br>
Gewapend met de kennis van de tovenaar en de kracht van de amulet, ging Stefan terug het bos in. Hij vocht tegen de duistere kracht en versloeg uiteindelijk de bron van het kwaad, waardoor het bos weer veilig werd voor alle wezens die erin leefden.
<br><br>
Toen Stefan terugkeerde naar zijn dorp, werd hij als een held onthaald. Maar het enige wat hij kon denken, was aan de magische wereld die hij ontdekt had en de vrienden die hij gemaakt had tijdens zijn avontuur. Vanaf die dag beloofde Stefan zichzelf dat hij altijd op zoek zou blijven gaan naar de magie in de wereld om hem heen.', 'I2SD1', 'stefan.vet', 'stefan.vet'),
('Collin', 17, 'Er was eens een jongen genaamd Collin. Hij woonde in een kleine stad aan de rand van een uitgestrekte oceaan. Collin was altijd al gefascineerd geweest door de verhalen die zijn grootvader hem vertelde over de mysterieuze wezens die in de oceaan leefden.
<br><br>
Op een dag besloot Collin een boot te huren en de oceaan op te gaan, op zoek naar avontuur. Terwijl hij verder wegvoer van de kust, begon hij te merken dat er iets vreemds aan de hand was. De golven werden hoger en wilder, en de wind begon aan te trekken. Het leek alsof er een vreemde kracht in de oceaan was die hem naar binnen trok.
<br><br>
Plotseling doemde er een gigantische draaikolk op voor zijn boot en voordat hij het wist, werd hij meegesleurd in de wirbelende stroom van water. Terwijl hij ronddraaide, zag Collin een glimp van een prachtige onderwaterwereld, vol met kleurrijke vissen, koraalriffen en mysterieuze wezens.
<br><br>
Toen de draaikolk eindelijk tot stilstand kwam, bevond Collin zich in een grot diep onder de oceaan. Hij zag een schitterende stad, die verlicht werd door gloeiende kwallen en heldere algen. Collin kwam er al snel achter dat deze stad werd bewoond door zeemeerminnen, met hun lange vinnen en fonkelende schubben.
<br><br>
Een van de zeemeerminnen, genaamd Coral, sprak Collin aan en vertelde hem dat hij was uitgekozen om de stad te helpen beschermen tegen een kwaadaardige tovenaar die probeerde de stad over te nemen. Collin, die vastbesloten was om te helpen, ging op zoek naar de tovenaar.
<br><br>
Na een epische strijd, waarbij hij gebruik maakte van zijn moed en slimheid, versloeg Collin de tovenaar en redde daarmee de stad. Coral en de andere zeemeerminnen bedankten hem en gaven hem een magisch amulet dat hem de kracht gaf om te ademen onder water.
<br><br>
Toen Collin terugkeerde naar de oppervlakte, was hij veranderd. Hij had een gevoel van avontuur en opwinding dat hij nog nooit had gevoeld. Vanaf dat moment besloot Collin dat hij altijd op zoek zou blijven gaan naar de geheimen van de oceaan en de magie die erin verborgen lag. Hij wist dat er nog zoveel te ontdekken viel en dat hij klaar was voor alle uitdagingen die op zijn pad zouden komen.', 'I2SD1', 'collin570_', 'collin-0570'),
('Daan', 17, 'In een ver land, ver weg van hier, leefde een jongen genaamd Daan. Daan was altijd gefascineerd geweest door de magie van de wereld om hem heen. Hij vond het geweldig om verhalen te lezen over tovenaars, draken en andere fantastische wezens.
<br><br>
Op een dag, terwijl Daan in het bos aan het wandelen was, ontdekte hij een mysterieuze deur verborgen tussen de bomen. Hij was nieuwsgierig en besloot de deur te openen. Hij stapte door de deur en kwam terecht in een magische wereld.
<br><br>
De lucht was gevuld met fonkelende sterren en de bomen waren bedekt met glinsterende kristallen. Daan keek om zich heen en zag dat hij niet alleen was. Er waren elfen, feeën en andere magische wezens om hem heen. Ze groetten hem vriendelijk en Daan realiseerde zich dat hij nu in het rijk van de magie was.
<br><br>
Een elf genaamd Arin stelde zich voor aan Daan en nam hem mee op een reis door de betoverde wereld. Ze vlogen door de lucht op de rug van een gigantische draak en landden in een prachtige tuin gevuld met bloemen en geurige kruiden.
<br><br>
Daar ontmoetten ze een tovenaar genaamd Merlijn, die Daan de basisprincipes van magie bijbracht. Daan ontdekte dat hij een natuurlijke gave had voor het beheersen van magie en hij was vastbesloten om deze gave verder te ontwikkelen.
<br><br>
Daan begon aan zijn opleiding als tovenaar en leerde snel de geheimen van de magie. Hij leerde spreuken uit te spreken en kon de elementen manipuleren om zijn wil te gehoorzamen. Hij ging op avontuurlijke missies om de vrede in de betoverde wereld te bewaren en te beschermen tegen kwaadaardige wezens die de harmonie wilden verstoren.
<br><br>
Jaren gingen voorbij en Daan werd een van de meest getalenteerde tovenaars van het land. Hij was geliefd bij alle magische wezens en werd gerespecteerd door de hele betoverde wereld. Op een dag, terwijl hij naar de zonsondergang keek, realiseerde Daan zich dat hij zijn magische gave had gebruikt om de wereld een betere plek te maken.
<br><br>
Daan keerde terug naar de normale wereld, maar zijn ervaringen in de betoverde wereld bleven bij hem. Hij besloot om zijn magische gave te blijven gebruiken om de wereld om hem heen te helpen en te beschermen tegen kwaad. En zo werd Daan een held in zowel de magische wereld als de gewone wereld.', 'I2SD1', 'daan.07444', 'dw1234.0'),
('Senna', 17, 'In een magisch koninkrijk, omringd door glooiende heuvels en uitgestrekte bossen, woonde een jong meisje genaamd Senna. Ze was een zeer bijzonder meisje, want ze was gezegend met een gave die maar weinigen in het koninkrijk hadden: ze kon praten met dieren.
<br><br>
Sennas gave was niet onopgemerkt gebleven. Op een dag kwam er een uil naar haar toe die haar vertelde dat de dieren in het koninkrijk in gevaar waren. Een boze tovenaar was bezig met het vervuilen van de bossen en vergiftigde de rivieren. De dieren hadden iemand nodig om hen te helpen, en ze wisten dat Senna de enige was die de tovenaar kon stoppen.
<br><br>
Senna aarzelde geen moment en besloot om de dieren te helpen. Ze verzamelde haar moed en ging op pad, vergezeld door een groep dieren die haar wilden helpen. Ze ontmoetten allerlei dieren onderweg, van kleine muizen tot majestueuze herten. Elk dier dat ze tegenkwamen vertelde haar hun verhaal en hoe ze getroffen waren door de tovenaar.
<br><br>
Met de hulp van haar nieuwe vrienden kwam Senna eindelijk aan bij het kasteel van de tovenaar. Ze wist dat ze niet kon winnen van de tovenaar door brute kracht, dus besloot ze om haar gave te gebruiken en met de dieren samen te werken. Ze zond een boodschap uit naar alle dieren in de omgeving, en ze kwamen in grote getale om Senna te helpen.
<br><br>
Samen slaagden ze erin om de tovenaar te stoppen. Senna wist de tovenaar te overtuigen van zijn fouten en hem te laten inzien dat de dieren een belangrijk onderdeel waren van het koninkrijk. De tovenaar stopte met zijn vernietigende daden en hielp Senna en de dieren om de natuur te herstellen.
<br><br>
Senna keerde terug naar haar huis, maar haar avontuur was nog lang niet voorbij. Ze wist dat ze haar gave moest blijven gebruiken om de dieren in het koninkrijk te beschermen en te helpen. En zo werd Senna een legende in het koninkrijk, een heldin die werd bewonderd en gerespecteerd door alle dieren en mensen.', 'I2SD1', '074_senna', '(geen)');

/* BMW */
INSERT INTO `cars` (`type`, `model`, `image_url`, `price`, `color`, `amount`, `engine`, `horse_power`, `year_of_release`, `summary`)
VALUES 
('BMW', 'X1 sDrive18i', 'bmw-x1.png', 49394, 'bruin', 10, 'benzine', '162', 2009, 'De X1 heeft een soepele, atletische wegligging, een krachtige turbomotor met pittige acceleratie en verrassend laag brandstofverbruik voor zijn klasse. Automatische transmissie met handmatige functies geeft u het beste van twee werelden.'),
('BMW', 'X2 xDrive20i', 'bmw-x2.png', 59063.30, 'wit', 10, 'diesel', '178', 2018, 'De X2 is een van de meest betrouwbare gezins-SUVs die er is, met een indrukwekkende score van 97,7% in onze What Car? Betrouwbaarheidsonderzoek.'),
('BMW', 'X3 xDrive30e', 'bmw-x3.png', 67205.80, 'wit', 10, 'elektrisch', '292', 2021, 'De 2021 BMW X3 plug-in hybride wordt geleverd in slechts één uitvoering, genaamd xDrive30e. Hij wordt aangedreven door een viercilinder turbomotor gekoppeld aan een plug-in hybride systeem. Het totale vermogen bedraagt ​​288 pk en 310 lb-ft koppel. Het vermogen wordt via een automatische achtversnellingsbak naar alle vier de wielen geleid.'),
('BMW', 'X4 xDrive20i', 'bmw-x4.png', 74389.80, 'wit', 10, 'benzine', '184', 2015, 'BMW X4 is een SUV met 5 zitplaatsen. Hij is verkrijgbaar in 4 varianten, motoropties van 1998 tot 2993 cc en 1 transmissieoptie: automaat (TC). Andere belangrijke specificaties van de X4 zijn een bodemvrijheid van 204 mm, een leeggewicht van 1795 kg en een bagageruimte van 525 liter.'),
('BMW', 'X5 xDrive50e', 'bmw-x5.png', 100857.40, 'groen', 10, 'elektrisch', '489', 2023, 'De X5 xDrive45e biedt een geprojecteerd elektrisch bereik van 50 kilometer, meer dan middelgrote concurrenten, maar het door de EPA geschatte brandstofverbruik in hybride modus is verschrikkelijk met 20 mpg gecombineerd. Dat is beduidend slechter dan sommige concurrenten en slechter dan de gewone zescilinder X5.'),
('BMW', 'X6 M60i xDrive', 'bmw-x6.png', 175009.60, 'groen', 10, 'benzine', '530', 2023, 'Elke X6 is standaard uitgerust met xDrive, het intelligente vierwielaandrijvingssysteem van BMW, dat automatisch het vermogen over de wielen verdeelt voor optimale tractie en controle.'),
('BMW', 'X7 xDrive40i', 'bmw-x7.png', 140280.30, 'wit', 10, 'benzine', '381', 2019, 'De BMW X7 wordt standaard geleverd met Active Driving Assistant, waaronder veiligheidssystemen als Active Blind Spot Detection, Frontal Collision Warning met City Collision Mitigation en Lane Departure Warning. Het optionele Driving Assistance Professional-pakket is ook beschikbaar, inclusief Frontal Collision Warning met City Collision Mitigation en Extended Traffic Jam Assistant.'),
('BMW', 'Z4 sDrive20i', 'bmw-z4.png', 63737, 'paars', 10, 'benzine', '197', 2023, 'BMW Z4 sDrive 20i is de benzinevariant in de BMW Z4-serie. Het levert een gecertificeerde kilometerstand van 14,3 kmpl op. Deze sDrive 20i-variant is het BMW Z4-basismodel en wordt geleverd met een motor die 194 pk levert bij 4500 tpm en 320 Nm bij 1450 tpm aan respectievelijk maximaal vermogen en maximaal koppel.'),
('BMW', 'i8', 'bmw-i8.jpg', 147500, 'zwart', 10, 'elektrisch', '231', 2023, 'De BMW i8 was het eerste productiemodel van BMW dat werd aangedreven door een driecilinder benzinemotor en het resulterende specifieke vermogen van 115 kW (154 pk) per liter cilinderinhoud was vergelijkbaar met high-performance sportwagenmotoren en was het hoogste van alle elke motor geproduceerd door de BMW Group.'),
('BMW', ' XM', 'bmw-xm.png', 181274.30, 'blauw', 10, 'elektrisch', '653', 2023, 'De BMW XM is een plug-in hybride elektrische full-size luxe cross-over SUV vervaardigd door BMW onder de BMW M-dochteronderneming. Het is de tweede auto die volledig door BMW M is ontwikkeld, na de BMW M1 in 1978. Een krachtigere versie, genaamd "Label Red", werd ook aangekondigd naast de onthulling van de XM op 27 september 2022.'),
('BMW', '1 Series', 'bmw-1-serie.png', 37142.40, 'blauw', 10, 'benzine', '109', 2020, 'Ontdek de BMW 1 Serie. De compacte BMW onderscheidt zich met een onmiskenbaar design, sportiviteit en baanbrekende technologieën. Het is in ieder opzicht een echte BMW en staat dus garant voor een dynamische rijbeleving.'),
('BMW', '218i Coupé', 'bmw-2-serie.png', 49637.30, 'wit', 10, 'benzine', '156', 2021, 'het is de minst krachtige BMW-auto in het gamma met slechts drie cilinders, 140 pk en 220 Nm, maar geloof me als ik zeg dat hij allesbehalve traag is. Deze auto is zelfs sneller en rijdt veel beter dan veel andere autos op onze wegen'),
('BMW', '320d Sedan', 'bmw-3-serie.png', 52158.80, 'wit', 10, 'diesel', '122', 2018, 'U profiteert van een hoogwaardige standaarduitrusting en de typische BMW rijdynamiek.'),
('BMW', '420i Coupé', 'bmw-4-serie.png', 57920.30, 'wit', 10, 'benzine', '184', 2019, 'De prestaties van de 4-serie zijn sterk, met de 181 pk sterke 420i-benzineversie die een tijd van 0-100 km/u in 7,5 seconden aflegt. De 430i (niet meer beschikbaar op de prijslijst) ziet een vermogenstoename tot 254 pk en een verbeterde sprint naar 100 km/u in slechts 5,8 seconden.'),
('BMW', '518d Sedan', 'bmw-5-serie.png', 65122.20, 'wit', 10, 'diesel', '150', 2020, 'De BMW 5 Serie bouwt verder op zijn efficiëntievoorsprong in de executive klasse. Nieuwe generatie viercilinder dieselmotoren met BMW TwinPower Turbo-technologie verhogen het rijplezier van de wereldwijde bestseller en zorgen voor een verdere verlaging van het brandstofverbruik en de emissies – De nieuwe BMW 520d overtreft zijn segmentrivalen in de efficiëntierace: motorvermogen stijgt tot 140 kW/190 pk, het gemiddelde brandstofverbruik daalt tot slechts 4,1 l/100 km en de CO2-uitstoot tot 109 g/km.'),
('BMW', 'M3', 'bmw-m3.jpg', 75295, 'grijs', 10, 'benzine', '240', 1995, 'De eerste M3 werd gemaakt als homologatiespecial op basis van de 3-serie coupé, zodat BMW hem kon gebruiken om deel te nemen aan verschillende toerwagenkampioenschappen over de hele wereld. Er moesten er slechts 5.000 worden geproduceerd om aan de Groep A-voorschriften te voldoen, maar uiteindelijk rolden er bijna 18.000 de fabriek uit.');
/* audi */
INSERT INTO `cars` (`type`, `model`, `image_url`, `price`, `color`, `amount`, `engine`, `horse_power`, `year_of_release`, `summary`)
VALUES
('audi', 'Q8 e-tron', 'Q8 e-tron.png', 71385, 'grijs', 4, 'elektrisch', '408', 2023, 'De Q8 e-tron is net zo executive als je hier zou verwachten. Zelfs de basisafwerking van de Q8 e-tron is zo goed uitgerust dat je je nauwelijks kunt voorstellen hoe Audi er nog meer spullen in zou kunnen rammen en de prijs zou kunnen opdrijven (spoiler: het lukt). Je krijgt 20-inch wielen, luchtvering, LED-koplampen, een elektrisch te openen kofferbak, elektrisch verstelbare verwarmde voorstoelen, alle touchscreens die je maar kunt wensen en 360 graden parkeersensoren.'),
('audi', 'A1 Sportback', 'a1.png', 30000, 'zwart', 10, 'diesel', '149', 2008, 'De tweede generatie van de A1 Sportback heeft een volledig nieuw en karakteristiek design, daarbij geeft de A1 een knipoog naar de eerste Audi quattro. De A1 Sportback is niet alleen de sportiefste in zijn klasse, maar zet ook de maatstaf voor de rest in de klasse van compacte autos absolute topkwaliteit.'),
('audi', 'AG', 'audi-AG.png', 100000, 'grijs', '1', 'diesel', '50', 2010, 'Audi AG kan terugkijken op een gevarieerde en bewogen geschiedenis, waarvan de traditie teruggaat tot de 19e eeuw. Tijdens een eerste concentratiegolf in de auto-industrie fuseerde Audi in 1932 met Horch, DKW en Wanderer tot Auto Union AG. De vier met elkaar verweven ringen van het Audi-logo doen nog steeds denken aan de stichtende merken. Vandaag is Audi een van de belangrijkste Duitse premiummerken naast Mercedes-Benz en BMW. Werner Oswald volgt in deze bundel de geschiedenis van deze opkomst en de modellen waarmee Auto Union en zijn erfgenamen deze prestatie hebben geleverd.'),
('audi', 'A3 Sportback', 'audi-A3-sportback.png', 37500, 'blauw', 10, 'benzine', '115', 2010, 'De 4e generatie van de Audi A3 is niet vernieuwend en biedt geen unieke voorzieningen. Toch weet de auto zich te onderscheiden met verfijning in de vormgeving en de rijeigenschappen.'),
('audi', 'A4 Avant', 'audi-A4.png', 37140, 'grijs', 15, 'benzine', '265', 2014, 'Audi presenteert de 5e generatie van de A4. De A4 rijdt prima, maar niet beter dan gemiddeld. De techniek is modern, maar niet vooruitstrevend. Het strakke uiterlijk is en blijft het sterkste punt.'),
('audi', 'A5 Sportback', 'a5-sportback.png', 43285, 'grijs', 14, 'benzine', '150', 2018, 'De Audi A5 Coupe ziet er niet alleen goed uit, maar rijdt ook zo. Enige vorm van "voorsprong door techniek" is ver te zoeken, maar door bestaande techniek te verfijnen is de A5 sportief en comfortabel'),
('audi', 'A6', 'audi-a6.png', 61245, 'grijs', 10, 'diesel', '204', 2018, 'De nieuwe Audi A6 (2018) is niet wezenlijk anders dan de vorige, maar doet alles beter. Hij biedt meer comfort en tegelijkertijd meer dynamiek. De semi-zelfrijdende functies maken de auto veiliger.'),
('audi', 'A7', 'audi-a7.png', 89315, 'grijs', 10, 'benzine', '340', 2018, 'De Audi A7 Sportback combineert de geavanceerde elektronica van het topmodel met de dynamiek van de andere modellen. Het lijnenspel combineert een 4-deurs sedan met een coupe.'),
('audi', 'A8', 'audi-a8.png', 105695, 'grijs', 10, 'benzine', '340', 2017, 'De Audi A8 is klaar voor de toekomst met hybride aandrijving en verregaande zelfrijdende functies. Zonder die opties scoort de A8 vooral met het comfort en de rijeigenschappen.'),
('audi', 'Q2', 'audi-q2.png', 31145, 'geel', 5, 'benzine', '116', 2016, 'De Q2 is de compacte, betaalbare SUV van Audi. De Q2 overtuigt met uitstekende rijeigenschappen en een geweldige 1.0 TFSI motor. Helaas zijn de 1.6 diesel en de materiaalkeuze minder.'),
('audi', 'Q3', 'audi-q3.png', 44220, 'blauw', 10, 'benzine', '150', 2018, 'De Audi Q3 is de droomauto voor perfectionisten. Alles is mooi, alles werkt perfect. Dat is goed, maar het maakt deze SUV weinig avontuurlijk en zelfs een tikkeltje saai.'),
('audi', 'Q4', 'audi-q4.png', 52105, 'zwart', 23, 'elektrisch', '170', 2021, 'De Q4 is een elektrisch aangedreven SUV volgens Audi: vertrouwd en toch modern. Vlot en toch dynamisch. Prima rijeigenschappen, groot bereik, moderne uitrusting. Een aanrader!'),
('audi', 'Q5', 'audi-q5.png', 59700, 'grijs', 8, 'benzine', '245', 2017, 'De Audi Q5 onderscheidt zich met verfijning en sublieme rijeigenschappen. De Q5 is geen terreinauto, maar een extra stoere zakenauto. Kostbare opties noodzakelijk voor een complete auto.'),
('audi', 'Q7', 'audi-q7.png', 83090, 'grijs', 8, 'benzine', '340', 2015, 'De Audi Q7 voor modeljaar 2020 biedt de laatste techniek die Audi in huis heeft. De Q7 combineert dat met maximaal comfort, volop ruimte en (beperkte) terreinwaardigheid.'),
('audi', 'TT', 'audi-tt.png', 44340, 'blauw', 15, 'benzine', '180', 2014, 'De nieuwe TT is het paradepaardje van Audi. Zowel de vormgeving als de ergonomie zijn echt innovatief. Daarbij is de nieuwe TT comfortabeler en tegelijk sportiever dan voorheen.'),
('audi', 'R8', 'audi-r8.png', 238940, 'geel', 5, 'benzine', '540', 2015, 'De Audi R8 is een supersportwagen die zich leent voor dagelijks gebruik en voor snelle rondetijden op het circuit. Vanaf modeljaar 2019 nog sneller en nog makkelijker te rijden.');
/* mercedes */
INSERT INTO `cars` (`type`, `model`, `image_url`, `price`, `color`, `amount`, `engine`, `horse_power`, `year_of_release`, `summary`)
VALUES
('mercedes', 'A-klasse', 'a-classe.png', 31466, 'grijs', 10, 'benzine', '109', 2018, 'De Mercedes-Benz A250e biedt dankzij plug-in hybride aandrijving het beste van twee werelden. De A250e is snel en dynamisch indien gevraagd, maar comfortabel en zuinig bij dagelijks gebruik.'),
('mercedes', 'CLA', 'cla.png', 37466, 'zwart', 10, 'diesel', '116', 2019, 'De Mercedes-Benz CLA wil een jonge doelgroep aanspreken en doet dat overtuigend met een extravagant uiterlijk, sportieve rijeigenschappen (CLA 220) en een moderne, vooruitstrevende uitrusting.'),
('mercedes', 'CLA Shooting Brake', 'CLA Shooting Brake.png', 38918, 'zwart', 5, 'benzine', '136', 2019, 'De Mercedes-Benz CLA Shooting Brake is een stationcar met de lijnen van een coupe. Rijdt scherp en sportief. Ook als CLA 200 comfortabel en vlot.'),
('mercedes', 'C-Klasse', 'c-klasse.png', 48280, 'grijs', 10, 'benzine', '170', 2021, 'Met de 5e generatie van de C-Klasse geeft Mercedes-Benz een moderne interpretatie aan de traditionele sedan. Mild-hybrid maakt de C180 zuinig. MBUX 2.0 is krachtig en toch eenvoudig te bedienen.'),
('mercedes', 'C-Klasse Estate', 'C-Klasse Estate.png', 54649, 'grijs', 10, 'benzine', '170', 2021, 'De Mercedes-Benz C-Klasse Estate combineert een moderne uitrusting met ruimte en comfort. De motoren zijn conventioneel. De C200 leent zich zowel voor comfort als dynamiek.'),
('mercedes', 'E-Klasse Estate', 'E-Klasse Estate.png', 63536, 'wit', 10, 'benzine', '184', 2016, 'De nieuwe Mercedes-Benz E-Klasse Estate onderscheidt zich met luxe, veiligheid en ruimte dankzij een intelligent ontwerp. De E400 biedt nog meer comfort omdat met groot gemak wordt gepresteerd.'),
('mercedes', 'E-Klasse', 'e-klasse.png', 59735, 'grijs', 10, 'benzine', '184', 2016, 'De Mercedes-Benz E300e biedt dankzij hybride aandrijving meer comfort, betere prestaties dan een gewone E-Klasse. Het verbruik is desondanks laag tot nul. Alleen maar voordelen!'),
('mercedes', 'E-Klasse Coupe', 'E-Klasse Coupe.png', 58812, 'grijs', 10, 'benzine', '197', 2017, 'Mercedes-Benz heeft goed werk geleverd met de E-Klasse Coupe, want de auto rijdt en voelt echt anders dan de sedan. Uiteraard beschikt de coupe wel dezelfde vooruitstrevende techniek.'),
('mercedes', 'S-Klasse', 'S-Klasse.png', 130682, 'zwart', 10, 'benzine', '435', 2020, 'De 7e generatie van de Mercedes S-Klasse legt de nadruk op de uitrusting en de rijeigenschappen, nu elektrische autos al ultiem comfort bieden. Veel vernieuwing en pure verwennerij voor de passagiers'),
('mercedes', 'SL', 'SL.png', 161696, 'rood', 10, 'benzine', '381', 2022, 'Met de SL zet Mercedes een oude traditie voort in de nieuwe tijd. Op het gebied van vormgeving, ergonomie, veiligheid en luxe is dat gelukt. De V8 is niet van deze tijd en maakt de SL onnodig kostbaar'),
('mercedes', 'GT', 'GT.png', 190867, 'zwart', 1, 'benzine', '476', 2014, 'De Mercedes-AMG GT combineert het comfort en de beschaafde lijnen met een Gran Turismo, met de prestaties en de sensatie van een supersportwagen.'),
('mercedes', 'B-Klasse', 'B-Klasse.png', 48087, 'wit', 15, 'benzine', '136', 2019, 'De Mercedes-Benz B-Klasse combineert ruimte met luxe. De rijeigenschappen zijn voldoende. De vele comfort-functies maken de B-Klasse tot een bijzondere auto.'),
('mercedes', 'G-Klasse', 'G-Klasse.png', 188220, 'wit', 5, 'diesel', '286', 2018, 'De Mercedes-AMG G63 is een auto van extremen. De G-Klasse is sterk in het terrein en razendsnel op de autobahn. De uitrusting is vergelijkbaar met die van een S-Klasse.'),
('mercedes', 'GLE Coupe', 'GLE Coupe.png', 125623, 'grijs', 5, 'diesel', '330', 2020, "De Mercedes-Benz GLE Coupe onderscheidt zich van andere luxe SUV's met zowel een meer sportief karakter als een bijzonder lijnenspel. Dit doet geen afbreuk aan de ruimte of terreinwaardigheid."),
('mercedes', 'GLS', 'GLS.png', 129228, 'grijs', 5, 'diesel', '330', 2020, 'De GLS is niet alleen de grootste SUV van Mercedes, maar ook van Nederland. De binnenruimte is enorm en wordt gecombineerd met de luxe van een topklasse reisauto. Kostbaar in aanschaf en gebruik.'),
('mercedes', 'GLA', 'GLA.png', 49267, 'grijs', 5, 'benzine', '163', 2020, 'De Mercedes-Benz GLA 250 e is een plug-in hybride die het beste biedt van vele werelden. Deze SUV is ruim en praktisch, vlot en zuinig, stil en comfortabel, sportief en comfortabel.')
/* volkswagen */
INSERT INTO `cars` (`type`, `model`, `image_url`, `price`, `color`, `amount`, `engine`, `horse_power`, `year_of_release`, `summary`)
VALUES
('volkswagen', 'Polo', 'Polo.png', 19990, 'wit', 15, 'benzine', '80', 2017, 'De Volkswagen Polo GTI is functioneel en comfortabel wanneer het moet, maar razendsnel en spectaculair wanneer het mag. De GTI is snel, maar voelt nog sneller dan hij is dankzij het brute karakter.'),
('volkswagen', 'Taigo', 'Taigo.png', 28590, 'groen', 12, 'benzine', '95', 2021, 'De Volkswagen Taigo is een compacte SUV met de daklijn van een coupe. Dat gaat nauwelijks ten koste van de binnenruimte, maar de rijeigenschappen verschillen slechts op details van andere Volkswagens.'),
('volkswagen', 'T-Cross', 'T-Cross.png', 29400, 'zwart', 14, 'benzine', '95', 2019, 'De T-Cross is de compacte SUV van Volkswagen. Veel aandacht voor infotainment, veiligheid en uiterlijk. Het mechaniek is behoudend en grotendeels gelijk aan dat van de VW Polo'),
('volkswagen', 'Golf', 'Golf.png', 34990, 'geel', 10, 'benzine', ' 110', 2020, 'De Volkswagen Golf GTE biedt een slaagde combinatie van elektrische en conventionele aandrijving. De GTE is vlot en sportief, maar heeft het zorgeloze bereik van een auto met benzinemotor.'),
('volkswagen', 'Golf Variant', 'Golf Variant.png', 28690, 'geel', 5, 'benzine', '110', 2021, 'De Variant biedt dankzij een verlengde wielbasis en extra overhang meer ruimte dan de standaard Golf. De uitrusting is modern en de eTSI motor relatief vlot en zuinig. Moderne uitrusting.'),
('volkswagen', 'ID.3', 'ID.3.png', 33990, 'grijs', 8, 'elektrisch', '150', 2020, "De Volkswagen ID.3 is de auto die elektrisch rijden gewoon maakt. De ID.3 biedt alle voordelen die andere elektrische auto's bieden, maar maakt ze toegankelijker dankzij de prijs en verpakking."),
('volkswagen', 'Passat', 'Passat.png', 39575, 'grijs', 10, 'elektrisch', '218', 2014, 'De Volkswagen Passat zet wederom de standaard. De Passat is verfijnd, snel en luxueus, maar straalt elegantie en eenvoud uit; precies wat anno 2014 van een zakenauto wordt gevraagd.'),
('volkswagen', 'Passat Variant', 'Passat Variant.png', 41270, 'grijs', 10, 'elektrisch', '218', 2014, 'Niet vernieuwend, niet bijzonder en niet opvallend. Tegelijkertijd ruim, praktisch, comfortabel en modern waardoor de nieuwe Volkswagen Passat perfect aansluit bij de wensen van de zakelijke rijder'),
('volkswagen', 'Arteon', 'Arteon.png', 48950, 'grijs', 10, 'benzine', '190', 2017, 'De Volkswagen Arteon is de eerste vierdeurs coupé van een alledaags merk. Gezien de prijs is de 1.5 TSI een prima aanbod en rijdt de auto zo goed als hij er uitziet.'),
('volkswagen', 'Arteon Shooting Brake', 'Arteon Shooting Brake.png', 49490, 'blauw', 10, 'benzine', '190', 2020, 'De Volkswagen Arteon start een tweede leven als Shooting Brake. Een exclusief interieur, een rijke uitrusting en plug-inhybride aandrijving maken de Arteon klaar voor de toekomst.'),
('volkswagen', 'T-Roc', 'T-Roc.png', 32790, 'wit', 10, 'benzine', '110', 2017, 'De Volkswagen T-Roc R is een sportieve versie van een alledaagse gezinsauto. De R is sensationeel snel, maar kostbaar in aanschaf en gebruik'),
('volkswagen', 'T-Roc Cabrio', 'T-Roc Cabrio.png', 36600, 'blauw', 10, 'benzine', '115', 2020, 'De Volkswagen T-Roc Cabriolet heeft geen uitgesproken rijeigenschappen, maar wel een uitgesproken karakter. Dit is een echte zonaanbidder die uitnodigt om zo veel mogelijk open te rijden.'),
('volkswagen', 'Tiguan', 'Tiguan.png', 36390, 'wit', 10, 'benzine', '130', 2016, 'De Volkswagen Tiguan vanaf modeljaar 2021 is bedoeld voor wie alles graag bij het vertrouwde laat. De uitrusting is gemoderniseerd en verder is alles bij het oude gebleven: op alle punten goed.'),
('volkswagen', 'Tiguan Allspace', 'Tiguan Allspace.png', 42290, 'zwart', 10, 'benzine', '150', 2017, 'De Volkswagen Tiguan AllSpace combineert het stoere uiterlijk van een SUV met de ruimte van een 5+2 persoons MPV. Moderne techniek, prima rijeigenschappen en zelfs vaardig in het terrein.'),
('volkswagen', 'Multivan', 'Multivan.png', 54500, 'oranje', 4, 'benzine', '218', 2022, 'De Volkswagen Multivan is een zeer grote gezinsauto die dankzij hybride-aandrijving hetzelfde kost als een vergelijkbare SUV. Dankzij personenauto-techniek biedt de Multivan bovengemiddeld comfort.'),
('volkswagen', 'ID.Buzz', 'ID.Buzz.png', 57132, 'geel', 3, 'elektrisch', '204', 2022, "De Volkswagen ID.Buzz combineert aantrekkelijke vormgeving met elektrische aandrijving. Het resultaat is een auto die ruimer, comfortabeler, stabieler en schoner is dan traditionele gezinsauto's.")
/* ford-pickup*/
INSERT INTO `cars` (`type`, `model`, `image_url`, `price`, `color`, `amount`, `engine`, `horse_power`, `year_of_release`, `summary`)
VALUES
('ford-pickup', 'Ford F-150', 'f-150.png', 55690, 'grijs', 5, 'benzine', '290', 2014, "De Ford F-150 is een populaire pickup truck van het Amerikaanse automerk Ford. Het voertuig is voor het eerst geïntroduceerd in 1948 en is sindsdien uitgegroeid tot een van de best verkopende auto's ter wereld."),
('ford-pickup', 'Ford Ranger', 'ford ranger.png', 35000, 'grijs', 5, 'benzine', '270', 2011, 'De Ford Ranger is een midsize pickup truck die wordt geproduceerd door het Amerikaanse automerk Ford. Het voertuig werd voor het eerst geïntroduceerd in 1983 en was tot 2011 beschikbaar in de Verenigde Staten, waarna de productie werd stopgezet. De Ranger werd echter in 2019 opnieuw geïntroduceerd in de VS en is momenteel verkrijgbaar in verschillende landen over de hele wereld. '),
('ford-pickup', 'Ford F-250 Super Duty', 'f-250.png', 55990, 'wit', 5, 'benzine', '475', 2008, 'De Ford F-250 is een heavy-duty pickup truck die wordt geproduceerd door het Amerikaanse automerk Ford. Het voertuig maakt deel uit van de Ford F-serie, die sinds 1948 op de markt is en bestaat uit verschillende modellen van lichte tot heavy-duty trucks.'),
('ford-pickup', 'Ford F-350 Super Duty', 'f-350.png', 69420, 'wit', 5, 'benzine', '385', 2012, 'De Ford F-350 is een heavy-duty pick-up truck die geproduceerd wordt door het Amerikaanse autobedrijf Ford. Het is een van de modellen in de Ford F-serie, die sinds 1948 op de markt is en bestaat uit verschillende modellen van lichte tot heavy-duty trucks.'),
('ford-pickup', 'Ford F-450 Super Duty', 'f-450.png', 42069, 'grijs', 5, 'benzine', '430', 2010, 'De Ford F-450 is een heavy-duty pick-up truck die geproduceerd wordt door het Amerikaanse autobedrijf Ford. Het is het grootste en krachtigste model in de F-serie en is ontworpen voor zware toepassingen, zoals het trekken van grote trailers of het vervoeren van zware ladingen.'),
('ford-pickup', 'Ford F-550 Super Duty', 'f-550.png', 55555, 'bruin', 5, 'diesel', '330', 2007, 'De Ford F-550 is een heavy-duty pick-up truck die geproduceerd wordt door het Amerikaanse autobedrijf Ford. Het is het grootste model in de F-serie en is ontworpen voor extreem zware toepassingen, zoals het trekken van grote trailers of het vervoeren van zware ladingen in ruwe omstandigheden. '),
('ford-pickup', 'Ford F-650 Super Duty', 'f-650.png', 64570, 'rood', 5, 'diesel', '330', 2015, 'De Ford F-650 is een zware vrachtwagen die geproduceerd wordt door het Amerikaanse autobedrijf Ford. Het is ontworpen voor commerciële toepassingen, zoals het vervoeren van zware vracht of het gebruik als werkvoertuig op bouwplaatsen.'),
('ford-pickup', 'Ford F-750 Super Duty', 'f-750.png', 80000, 'wit', 5, 'diesel', '300', 2005, 'De Ford F-750 is een zware vrachtwagen die geproduceerd wordt door het Amerikaanse autobedrijf Ford. Het is ontworpen voor commerciële toepassingen, zoals het vervoeren van zware vracht of het gebruik als werkvoertuig op bouwplaatsen.'),
('ford-pickup', 'Ford Courier', 'courier.png', 20000, 'zwart', 5, 'diesel', '100', 2018, 'De Ford Courier is een compacte pick-up truck die in verschillende markten over de hele wereld wordt verkocht. De Courier is ontworpen voor gebruik als een licht werkvoertuig, voor persoonlijk gebruik, of als een voertuig voor bezorgdiensten.'),
('ford-pickup', 'Ford Ranchero', 'ranchero.png', 120000, 'bruin', 2, 'diesel', '375', 1973, 'De Ford Ranchero was een pick-up truck-gebaseerde auto die werd geproduceerd door Ford Motor Company tussen 1957 en 1979. De Ranchero was een uniek concept dat de functionaliteit van een pick-up combineerde met de stijl en het comfort van een personenauto.'),
('ford-pickup', 'Ford Explorer Sport Trac', 'Ford Explorer Sport Trac.png', 15000, 'wit', 5, 'diesel', '292', 2010, 'De Ford Explorer Sport Trac is een mid-size pick-up truck die werd geproduceerd door Ford Motor Company van 2001 tot 2010. Het voertuig was gebaseerd op het chassis van de Ford Explorer SUV en combineerde de stijl en het comfort van een SUV met de functionaliteit en het laadvermogen van een pick-up truck.'),
('ford-pickup', 'Ford SVT Lightning', 'Ford SVT Lightning.png', 33000, 'rood', 5, 'diesel', '360', 2004, 'De Ford SVT Lightning was een high-performance pick-up truck die werd geproduceerd door Ford Motor Company van 1993 tot 1995 en van 1999 tot 2004. Het voertuig was ontworpen door de Special Vehicle Team (SVT) van Ford en was bedoeld om snelheid en prestaties te leveren, in combinatie met het gebruiksgemak van een pick-up truck.'),
('ford-pickup', 'Ford Raptor', 'raptor.png', 50000, 'wit', 5, 'diesel', '450', 2014, 'De Ford Raptor is een high-performance pick-up truck die is ontworpen en geproduceerd door Ford Motor Company. De truck is gebaseerd op de Ford F-150 en is ontworpen om off-road prestaties te leveren in combinatie met het gebruiksgemak van een pick-up truck.'),
('ford-pickup', 'Ford Bronco', 'bronco.png', 28500, 'grijs', 5, 'diesel', '310', 1988, 'De Ford Bronco is een off-road SUV die voor het eerst werd geproduceerd in 1966. Het voertuig werd geproduceerd tot 1996, toen het uit productie werd genomen. In 2020 werd de Bronco echter opnieuw geïntroduceerd als een geheel nieuw model voor het modeljaar 2021.'),
('ford-pickup', 'Ford SuperCab', 'supercab.png', 36500, 'zwart', 5, 'diesel', '325', 2014, 'De Ford SuperCab is een carrosserievariant van de Ford F-Series pick-up trucks, die worden geproduceerd door de Amerikaanse autofabrikant Ford Motor Company. De SuperCab is ontworpen om meer passagiersruimte en opbergruimte te bieden dan de reguliere cabinevarianten van de F-Series.'),
('ford-pickup', 'Ford Lobo', 'lobo.png', 35000, 'blauw', 5, 'diesel', '450', 2012, '"La Lobo" is de naam van de Ford F-150-pickuptruck in Mexico. Het is de best verkochte pick-uptruck in Mexico en wordt beschouwd als een belangrijk voertuig in de Mexicaanse auto-industrie. De naam "Lobo" betekent "wolf" in het Spaans.')
/* dodge */
INSERT INTO `cars` (`type`, `model`, `image_url`, `price`, `color`, `amount`, `engine`, `horse_power`, `year_of_release`, `summary`)
VALUES
('dodge', 'Challenger', 'Challenger.png', 80000, 'grijs', 4, 'diesel', '800', 1974, 'De Dodge Challenger is een muscle car die voor het eerst werd geïntroduceerd in 1970. Het was destijds een directe concurrent van de Ford Mustang en de Chevrolet Camaro. De Challenger was een groot succes en werd geproduceerd tot 1974.'),
('dodge', 'Charger', 'Charger.png', 65000, 'oranje', 1, 'diesel', '700', 1966, 'De Dodge Charger is een sedan met vier deuren en wordt geproduceerd sinds 1966. Het model werd oorspronkelijk ontworpen als muscle car, maar in de loop der jaren is de Charger geëvolueerd tot een krachtige sportieve sedan.'),
('dodge', 'Durango', 'Durango.png', 80000, 'zwart', 4, 'diesel', '700', 1997, 'De Dodge Durango is een full-size SUV die voor het eerst werd geïntroduceerd in 1997. Het is een van de grootste SUVs in het Dodge-portfolio en biedt plaats aan maximaal zeven passagiers. De Durango wordt geproduceerd met verschillende motoropties, waaronder een 3,6-liter V6, een 5,7-liter V8 en een 6,4-liter V8.'),
('dodge', 'Grand Caravan', 'Grand Caravan.png', 27000, 'grijs', 4, 'diesel', '283', 1983, 'De Dodge Grand Caravan is een minivan die voor het eerst werd geïntroduceerd in 1983. Het is een van de meest populaire modellen in het Dodge-portfolio en biedt plaats aan maximaal zeven passagiers. De Grand Caravan wordt geproduceerd met één motoroptie, namelijk een 3,6-liter V6.'),
('dodge', 'Journey', 'Journey.png', 30000, 'grijs', 4, 'diesel', '173', 2009, 'De Dodge Journey is een mid-size crossover SUV die voor het eerst werd geïntroduceerd in 2009. Het is een van de meest populaire modellen in het Dodge-portfolio en biedt plaats aan maximaal zeven passagiers. De Journey wordt geproduceerd met verschillende motoropties, waaronder een 2,4-liter viercilinder en een 3,6-liter V6.'),
('dodge', 'Neon', 'Neon.png', 4500, 'wit', 3, 'diesel', '132', 1994, 'De Dodge Neon is een compacte auto die werd geproduceerd van 1994 tot 2005. Het was een populaire keuze onder autokopers vanwege zijn aantrekkelijke ontwerp, betrouwbare prestaties en betaalbare prijs.'),
('dodge', 'Nitro', 'Nitro.png', 12500, 'bruin', 8, 'diesel', '260', 2007, 'De Dodge Nitro heeft een opvallend vierkantig ontwerp en heeft kenmerken die passen bij een typische SUV, zoals een hoge rijhoogte en een ruime cabine.'),
('dodge', 'Ram', 'Ram.png', 55000, 'zwart', 6, 'diesel', '305', 1981, 'De Dodge Ram is ontworpen als een robuuste pick-up truck met een stoere uitstraling. Hij heeft een vierkante carrosserie en is verkrijgbaar in verschillende cabine- en bedlengtecombinaties.'),
('dodge', 'Sprinter', 'Sprinter.png', 25345, 'wit', 5, 'diesel', '188', 2003, 'De Dodge Sprinter is een bestelwagen die oorspronkelijk in Europa werd geproduceerd door Mercedes-Benz en later werd verkocht onder de Dodge-merknaam in Noord-Amerika. De Sprinter is een van de populairste bestelwagens op de markt vanwege zijn betrouwbaarheid, veelzijdigheid en efficiëntie.'),
('dodge', 'Viper', 'Viper.png', 112000, 'zwart', 1, 'diesel', '645', 1992, 'De Dodge Viper is een high-performance sportwagen die voor het eerst werd geïntroduceerd in 1992. Het werd oorspronkelijk ontwikkeld als een conceptauto, maar de populariteit van de auto leidde tot de productie van de eerste generatie Viper in 1992.'),
('dodge', 'Avenger', 'Avenger.png', 7500, 'groen', 5, 'diesel', '235', 1995, 'De Dodge Avenger is een middelgrote sedan die werd geproduceerd door Dodge van 1995 tot 2014. De Avenger werd opnieuw geïntroduceerd in 2008 als een vervanging voor de Dodge Stratus en werd geproduceerd tot 2014. De auto is gebouwd op het Chrysler Sebring-platform en deelt veel technologie en componenten met die auto.'),
('dodge', 'Caliber', 'Caliber.png', 4500, 'rood', 3, 'diesel', '172', 2006, 'De Caliber werd geleverd met voorwielaandrijving en optionele vierwielaandrijving, afhankelijk van het model en de uitvoering. De auto had een ruim interieur en een veelzijdige achterklep die op verschillende manieren kon worden geopend en gebruikt. Standaard veiligheidsvoorzieningen op de Caliber waren onder meer voor- en zijairbags voor bestuurder en passagier, antiblokkeerremsystemen en een elektronisch stabiliteitsprogramma. Optionele functies waren onder meer een premium audiosysteem, een navigatiesysteem, Bluetooth-connectiviteit, een zonnedak en leren bekleding.'),
('dodge', 'Caravan', 'Caravan.png', 29000, 'bruin', 5, 'diesel', '215', 1984, 'De Dodge Caravan is een minivan die werd geproduceerd door het Amerikaanse automerk Dodge. De eerste generatie van de Caravan werd geïntroduceerd in 1984 en sindsdien zijn er verschillende modellen van deze auto geproduceerd.'),
('dodge', 'Colt', 'Colt.png', 7500, 'rood', 5, 'diesel', '86', 1970, 'De Colt is een compacte auto die van 1970 tot 2008 werd geproduceerd door de Japanse autofabrikant Mitsubishi. Het model werd in verschillende carrosserievarianten uitgebracht, waaronder een sedan, hatchback en stationwagen.'),
('dodge', 'Dakota', 'Dakota.png', 30000, 'blauw', 5, 'diesel', '295', 1987, 'De Dodge Dakota is een mid-size pick-up truck die sinds 1987 door Dodge wordt geproduceerd. Het is een van de oudste pick-up trucks in het Dodge-assortiment en heeft in de loop der jaren verschillende generaties gekend.'),
('dodge', 'Intrepid', 'Intrepid.png', 3500, 'rood', 15, 'diesel', '245', 1993, 'De Dodge Intrepid was een full-size sedan die tussen 1993 en 2004 werd geproduceerd. Het voertuig was ontworpen als een premium sedan die de concurrentie aanging met modellen zoals de Toyota Camry, Honda Accord en Ford Taurus.');
/* jeep */
INSERT INTO `cars` (`type`, `model`, `image_url`, `price`, `color`, `amount`, `engine`, `horse_power`, `year_of_release`, `summary`)
VALUES
('jeep', 'Wrangler', 'Wrangler.png', 65000, 'grijs', 5, 'diesel', '285', 2018, 'De Jeep Wrangler is een compacte SUV die bekend staat om zijn vermogen om off-road te gaan. Het is een iconisch model van het merk Jeep en heeft een lange geschiedenis die teruggaat tot de jaren 40 van de vorige eeuw, toen het werd ontwikkeld als een militair voertuig. De Wrangler is een van de meest herkenbare Jeeps vanwege zijn kenmerkende designelementen, zoals de zeven sleuven in de grille, ronde koplampen en de mogelijkheid om het dak en de deuren te verwijderen voor een open rij-ervaring.'),
('jeep', 'gladiator', 'gladiator.png', 75000, 'grijs', 5, 'diesel', '285', 2019, 'De Jeep Gladiator is een mid-size pick-up truck van het merk Jeep die werd geïntroduceerd in 2019. Het voertuig is gebaseerd op de Jeep Wrangler-platform en deelt veel van zijn designelementen en technologieën. De Gladiator is ontworpen om te voldoen aan de behoeften van klanten die op zoek zijn naar een off-road georiënteerde truck die ook geschikt is voor dagelijks gebruik.'),
('jeep', 'cherokee', 'cherokee.png', 55000, 'rood', 5, 'diesel', '180', 2014, 'De Jeep Cherokee is een mid-size SUV die voor het eerst werd geïntroduceerd in 1974 en sindsdien in verschillende varianten en generaties is geproduceerd. Het voertuig is ontworpen om zowel on- als off-road te presteren en is populair bij liefhebbers van avontuurlijke rijervaringen en gezinnen die een praktische en veelzijdige auto nodig hebben.'),
('jeep', 'grand cherokee', 'grand cherokee.png', 95000, 'grijs', 5, 'diesel', '475', 2010, 'De Jeep Grand Cherokee is een mid-size SUV die sinds 1993 in productie is. Het voertuig is ontworpen voor zowel on- als off-road rijden en biedt luxe functies en krachtige motoren. Het voertuig is populair bij liefhebbers van avontuurlijke rijervaringen en gezinnen die een ruime en comfortabele auto nodig hebben.'),
('jeep', 'renegade', 'renegade.png', 35000, 'grijs', 5, 'diesel', '140', 2014, 'De Jeep Renegade is een compacte SUV die in 2014 werd geïntroduceerd. Het voertuig is ontworpen voor stedelijke omgevingen en biedt off-road capaciteiten. Het voertuig is gebouwd op het platform van de Fiat 500X en wordt geproduceerd in de Melfi-fabriek in Italië.'),
('jeep', 'compass', 'compass.png', 40000, 'rood', 5, 'diesel', '140', 2017, 'De Jeep Compass is een compacte SUV die voor het eerst werd geïntroduceerd in 2007. Het voertuig is gebouwd op hetzelfde platform als de Jeep Renegade en de Fiat 500X en is ontworpen om een mix van on-road en off-road capaciteiten te bieden.'),
('jeep', 'patriot', 'patriot.png', 27750, 'grijs', 5, 'diesel', '172', 2011, 'De Jeep Patriot was een compacte SUV die werd geproduceerd tussen 2007 en 2017. Het was een van de goedkoopste modellen in het Jeep-gamma en werd gepositioneerd onder de Jeep Compass en de Jeep Cherokee.'),
('jeep', 'liberty(KJ)', 'liberty(KJ).png', 35000, 'grijs', 5, 'diesel', '210', 2002, 'De Jeep Liberty (KJ) was een compacte SUV die werd geproduceerd van 2002 tot 2007. Het was de vervanger van de Jeep Cherokee XJ en werd gepositioneerd tussen de kleinere Jeep Wrangler en de grotere Jeep Grand Cherokee.'),
('jeep', 'commander', 'commander.png', 454545, 'grijs', 5, 'benzine', '330', 2005, 'De Jeep Commander was een zevenzits SUV die werd geproduceerd van 2005 tot 2010. Het was het grootste voertuig in het Jeep-gamma en werd gepositioneerd tussen de Grand Cherokee en de Dodge Durango.'),
('jeep', 'Grand Wagoneer', 'grand wagoneer.png', 112000, 'zwart', 5, 'diesel', '144', 1963, "De Jeep Grand Wagoneer was een full-size SUV die tussen 1963 en 1991 werd geproduceerd en was een van de eerste luxe SUV's op de markt. In 2021 werd de naam Grand Wagoneer opnieuw geïntroduceerd als een premium SUV in het Jeep-gamma."),
('jeep', 'Wagoneer', 'wagoneer.png', 87560, 'multicolor', 5, 'diesel', '392', 1991, "De Jeep Wagoneer was een full-size SUV die werd geproduceerd van 1962 tot 1991. Het was een van de eerste SUV's op de markt en had een robuust ontwerp en uitstekende off-road mogelijkheden. In 2021 werd de naam Wagoneer opnieuw geïntroduceerd als een premium SUV in het Jeep-gamma."),
('jeep', 'CJ-5', 'CJ-5.png', 12750, 'grijs', 5, 'diesel', '125', 1960, 'De Jeep CJ-5 is een legendarische 4x4 off-road voertuig dat werd geproduceerd van 1955 tot 1983. Het was een van de populairste modellen van de CJ-serie van Jeep, en was zeer geschikt voor off-road gebruik vanwege zijn compacte formaat en wendbaarheid.'),
('jeep', 'CJ-7', 'CJ-7.png', 14690, 'wit', 5, 'diesel', '112', 1976, 'De Jeep CJ-7 is een compacte offroad-voertuig, geproduceerd door Jeep van 1976 tot 1986. Het voertuig was een doorontwikkeling van de CJ-5, met een iets langere wielbasis, verbeterde ophanging en een aantal nieuwe motoropties.'),
('jeep', 'CJ-8 Scrambler', 'CJ-8 scrambler.png', 35000, 'grijs', 5, 'diesel', '125', 1981, 'De Jeep CJ-8 Scrambler is een pickup-truckversie van de CJ-serie die werd geproduceerd van 1981 tot 1986. Het voertuig deelt veel van zijn ontwerpkenmerken met de CJ-7, waaronder de motoropties en de transmissies. Het belangrijkste verschil is de langere wielbasis, die zorgt voor een grotere laadruimte achter de cabine.'),
('jeep', 'Willys MB', 'willys mb.png', 50000, 'groen', 2, 'diesel', '60', 1941, 'De Willys MB is een legendarische Jeep die oorspronkelijk werd geproduceerd voor militair gebruik tijdens de Tweede Wereldoorlog. Het was een van de belangrijkste voertuigen die werden gebruikt door het Amerikaanse leger en speelde een belangrijke rol bij het winnen van de oorlog.'),
('jeep', 'Willys Overland', 'willys overland.png', 150000, 'geel', 1, 'diesel', '60', 1908, 'Willys-Overland is een Amerikaans automerk dat in 1908 werd opgericht door John North Willys. Het bedrijf produceerde aanvankelijk de Overland-auto, die al snel bekend werd om zijn betrouwbaarheid en kwaliteit. Na de Tweede Wereldoorlog richtte het bedrijf zich op de productie van terreinwagens, waaronder de Willys MB, die later de Jeep werd genoemd.')
/* lexus */
INSERT INTO `cars` (`type`, `model`, `image_url`, `price`, `color`, `amount`, `engine`, `horse_power`, `year_of_release`, `summary`)
VALUES
('lexus', 'ES', 'es.png', 45000, 'grijs', 8, 'benzine', '218', 1989, 'De Lexus ES is een luxe sedan die voor het eerst werd geïntroduceerd in 1989. Het is momenteel in zijn zevende generatie en wordt beschouwd als een van de meest populaire modellen van Lexus.'),
('lexus', 'LS', 'ls.png', 77000, 'zwart', 12, 'benzine', '416', 1989, 'De Lexus LS is het vlaggenschipmodel van Lexus, dat voor het eerst werd geïntroduceerd in 1989 en momenteel in zijn vijfde generatie is. Het is een luxe sedan met veel geavanceerde technologieën en een hoog niveau van comfort en prestaties. '),
('lexus', 'GS', 'gs.png', 55521, 'zwart', 12, 'benzine', '311', 1991, 'De Lexus GS is een luxe sedan die voor het eerst werd geïntroduceerd in 1991 en momenteel in zijn vierde generatie is. De GS is gepositioneerd tussen de compacte IS en de grotere LS en biedt een combinatie van sportieve prestaties en luxe functies. '),
('lexus', 'IS', 'is.png', 40000, 'rood', 5, 'benzine', '245', 1998, 'De Lexus IS is een compacte luxe sedan die voor het eerst werd geïntroduceerd in 1998 en momenteel in zijn derde generatie is. Het is gepositioneerd onder de Lexus GS en biedt een combinatie van luxe, comfort en sportieve prestaties'),
('lexus', 'RC', 'rc.png', 47000, 'grijs', 7, 'benzine', '241', 2014, 'De Lexus RC is een luxe sportcoupé die in 2014 werd geïntroduceerd als een alternatief voor de BMW 4-serie en Audi A5. Het is gebaseerd op de IS-sedan, maar heeft een eigen unieke uitstraling en is ontworpen om een sportieve rijervaring te bieden.'),
('lexus', 'LC', 'lc.png', 98000, 'wit', 1, 'benzine', '354', 2017, 'De Lexus LC is een luxe sportcoupé die in 2017 werd geïntroduceerd. Het is ontworpen om de rijprestaties van een sportauto te combineren met de luxe en het comfort van een GT-auto.'),
('lexus', 'UX', 'ux.png', 33000, 'grijs', 6, 'benzine', '169', 2018, "De Lexus UX is een compacte SUV die in 2018 werd geïntroduceerd. Het is ontworpen om te concurreren met andere premium SUV's in zijn klasse, zoals de BMW X1 en de Audi Q3. "),
('lexus', 'NX', 'nx.png', 41000, 'grijs', 5, 'benzine', '238', 2014, "De Lexus NX is een compacte SUV die voor het eerst werd geïntroduceerd in 2014 en sindsdien verschillende updates heeft ondergaan. Het is ontworpen om te concurreren met andere premium SUV's in zijn klasse, zoals de Audi Q5 en de BMW X3."),
('lexus', 'RX', 'rx.png', 50000, 'wit', 6, 'benzine', '295', 1998, 'De Lexus RX is een luxe SUV die voor het eerst werd geïntroduceerd in 1998 en sindsdien meerdere generaties heeft doorlopen. Het is momenteel een van de bestverkochte modellen van Lexus en biedt een combinatie van prestaties, comfort en betrouwbaarheid.'),
('lexus', 'GX', 'gx.png', 54000, 'grijs', 5, 'benzine', '301', 2002, 'De Lexus GX is een luxueuze SUV die voor het eerst werd geïntroduceerd in 2002. Het is een midsize SUV die plaats biedt aan maximaal zeven passagiers en die ontworpen is voor zowel on-road als off-road rijden. De GX heeft een stevig en robuust uiterlijk, met een opvallende grille en sterke lijnen die hem een ​​stoere en sportieve uitstraling geven.'),
('lexus', 'LX', 'lx.png', 89000, 'zwart', 9, 'benzine', '383', 1996, 'De Lexus LX is een luxueuze full-size SUV die voor het eerst werd geïntroduceerd in 1996. Het is ontworpen als een premium terreinwagen met uitstekende prestaties op en off-road, en biedt plaats aan maximaal acht passagiers in een ruim en comfortabel interieur.'),
('lexus', 'CT', 'ct.png', 32000, 'blauw', 6, 'benzine', '134', 2011, 'De Lexus CT is een compacte hybride hatchback die voor het eerst werd geïntroduceerd in 2011. Het is ontworpen als een premium auto met een hoge brandstofefficiëntie en een responsief rijgedrag.'),
('lexus', 'LFA', 'lfa.png', 375000, 'blauw', 2, 'benzine', '552', 2010, 'De Lexus LFA is een high-performance sportwagen die werd geproduceerd van 2010 tot 2012. Het was het eerste supercar-model van Lexus en er zijn slechts 500 exemplaren van geproduceerd.'),
('lexus', 'cs', 'cs.png', 28000, 'grijs', 7, 'benzine', '134', 2010, 'De Lexus CS (of Lexus CT in sommige markten) was een compacte hybride hatchback die van 2010 tot 2020 werd geproduceerd. Het was het eerste model van Lexus in dit segment en werd ontwikkeld als een premium alternatief voor andere hybride hatchbacks op de markt.'),
('lexus', 'HS', 'hs.png', 36750, 'grijs', 5, 'benzine', '187', 2009, 'De Lexus HS was een compacte sedan die tussen 2009 en 2012 werd geproduceerd. Het was een hybride model dat was gebaseerd op het Toyota Prius-platform. De auto werd geleverd met een 2,4-liter viercilinder benzinemotor, gekoppeld aan een elektromotor, wat resulteerde in een totaal gecombineerd vermogen van 187 pk. De HS was voorzien van een CVT-transmissie en was alleen beschikbaar met voorwielaandrijving.'),
('lexus', 'RC F', 'rc f.png', 100000, 'zwart', 2, 'benzine', '467', 2015, 'De Lexus RC F is een high-performance sportcoupé die sinds 2015 in productie is. Het model is gebaseerd op de Lexus RC, maar heeft een agressievere styling en is voorzien van een krachtiger motor. De RC F is gericht op rijplezier en prestaties en is ontworpen om te concurreren met andere sportcoupés in zijn klasse.');
/* landrover */
INSERT INTO `cars` (`type`, `model`, `image_url`, `price`, `color`, `amount`, `engine`, `horse_power`, `year_of_release`, `summary`)
VALUES
('landrover', 'Defender', 'defender.png', 696969, 'wit', 5, 'benzine', '135', 1983, 'De Land Rover Defender is een iconische 4x4 terreinwagen die in 1983 voor het eerst werd geïntroduceerd en tot 2016 in productie is gebleven. In 2020 werd een compleet vernieuwde versie op de markt gebracht.'),
('landrover', 'Discovery', 'discovery.png', 68000, 'oranje', 5, 'benzine', '249', 1989, 'De Land Rover Discovery is een grote, luxueuze SUV die voor het eerst in 1989 werd geïntroduceerd. Het voertuig wordt gepositioneerd tussen de compacte Range Rover Evoque en de full-size Range Rover modellen en is ontworpen als een veelzijdige auto die zowel on- als off-road uitstekende prestaties levert.'),
('landrover', 'Range Rover', 'range rover.png', 109000, 'bruin', 5, 'diesel', '339', 1970, 'De Range Rover is het vlaggenschipmodel van Land Rover en is een luxe SUV die voor het eerst werd geïntroduceerd in 1970. Het voertuig is bedoeld als een combinatie van ongeëvenaarde luxe, prestaties en off-road-capaciteiten.'),
('landrover', 'Range Rover Sport', 'rrs.png', 86000, 'rood', 5, 'benzine', '575', 2005, 'De Range Rover Sport is een luxe SUV van het Britse automerk Land Rover. Het model werd in 2004 geïntroduceerd en is sindsdien uitgegroeid tot een populaire keuze voor autoliefhebbers die op zoek zijn naar een combinatie van off-roadcapaciteiten en comfort op de weg.'),
('landrover', 'Range Rover Velar', 'rrv.png', 64000, 'wit', 5, 'benzine', '550', 2017, 'De Range Rover Velar is een luxe SUV van het Britse automerk Land Rover. Het model werd voor het eerst geïntroduceerd in 2017 en vult het gat tussen de Range Rover Evoque en de Range Rover Sport. Het ontwerp van de Velar is strak en modern en bevat veel geavanceerde technologie.'),
('landrover', 'Range Rover Evoque', 'rre.png', 65000, 'bruin', 5, 'benzine', '309', 2011, 'De Range Rover Evoque is een compacte luxe SUV van het Britse automerk Land Rover. Het model werd voor het eerst geïntroduceerd in 2011 en is sindsdien geëvolueerd naar een van de meest populaire voertuigen van het merk.'),
('landrover', 'Freelander', 'freelander.png', 30500, 'wit', 5, 'diesel', '190', 2005, 'De Land Rover Freelander is een compacte SUV die tussen 1997 en 2014 werd geproduceerd door het Britse automerk Land Rover.'),
('landrover', 'Series 1', 'Series 1.png', 35500, 'groen', 5, 'diesel', '52', 1952, 'Land Rover startte in 1948 de productie van de auto die later de Land Rover Series 1 genoemd zou worden. De introductie vond plaats op de AutoRai in Amsterdam. De Land Rover werd oorspronkelijk ontworpen voor gebruik op de boerderij en voor licht industrieel gebruik. De terreinwagen had een stalen ladderchassis en een aluminium carrosserie.'),
('landrover', 'Series 2', 'Series 2.png', 45000, 'groen', 5, 'diesel', '72', 1958, 'De opvolger van de succesvolle serie was ik de Series II, dat een oplage van 1958 tot 1961. Het kwam in 88 in (2200 mm) en 109 in (2800 mm) wielbasis (gewoonlijk aangeduid als de ‘SWB’ en ‘zag LWB). Dit was de eerste Land Rover om de aandacht van Rover styling afdelings- Chief Stylist ontvangt David Bache produceerde de bekende ‘barrel kant’ taille tot grotere spoorbreedte van het voertuig en het verbeterde ontwerp van de truck cab variant te dekken, de invoering van de gebogen zijruiten en afgerond dak nog steeds gebruikt op de huidige Land Rovers. De Series II was het eerste voertuig van de bekende 2,25-liter gebruiken benzinemotor, hoewel de eerste 1500 of zo korte wielbasis (SWB) modellen behouden de 52 pk (39 kW) 2.0-liter benzinemotor uit de Series I. Deze Grotere benzinemotor produceerde 72 pk (54 kW) en is nauw verwant met de 2,0-liter dieselmotor nog in gebruik. Deze motor werd de standaard Land Rover eenheid tot het midden van de jaren 1980, toen dieselmotoren steeds populairder.'),
('landrover', 'Series 3', 'Series 3.png', 34128, 'blauw', 5, 'diesel', '73', 1971, 'De Series III is de meest voorkomende versie van de Land Rover Series. In der periode van 1971 tot 1985 werden er 440.000 exemplaren van de SIII. Reeds bij de Late Series 2A (vanaf eind 1968 werden de koplampen verplaatst naar de vleugels (voorspatborden). Land Rover voerde als reden voor de aanpassing aan dat er diende te worden voldaan aan de Australische, Amerikaanse en Nederlandse regelgeving. De positie van de koplampen bleef onveranderd bij de Series III.'),
('landrover', '101 Forward Control', '101 Forward Control.png', 120000, 'groen', 2, 'benzine', '123', 1972, 'De Land Rover 101 Forward Control is een militaire vrachtwagen van het Britse automerk Land Rover. Het voertuig werd geproduceerd tussen 1972 en 1978 en werd ontwikkeld als een licht militair transportvoertuig voor het Britse leger.'),
('landrover', 'Lightweight', 'Lightweight.png', 145000, 'groen', 1, 'benzine', '68', 1968, 'De Land Rover Lightweight is een militaire voertuigvariant van de Land Rover Series, ontworpen en geproduceerd voor het Britse leger en andere militaire organisaties. Het voertuig werd geproduceerd tussen 1968 en 1984 en was bedoeld als lichtgewicht, mobiel transportvoertuig voor militairen. '),
('landrover', 'Wolf', 'Wolf.png', 245000, 'groen', 5, 'diesel', '134', 1998, 'De Land Rover Wolf is een militaire variant van de Land Rover Defender en wordt gebruikt door verschillende landen en militaire organisaties, waaronder het Britse leger. De afkorting "WOLF" staat voor "Wheel On Land, Fully-Fitted". '),
('landrover', 'Series 2A Fordward Control', 'Series 2A Fordward Control.png', 135000, 'groen', 2, 'benzine', '91', 1962, 'De Land Rover Series 2A Forward Control is een unieke variant van de Land Rover Series 2A, die tussen 1962 en 1972 werd geproduceerd. De term "Forward Control" verwijst naar de positie van de bestuurderscabine, die zich boven de vooras van het voertuig bevindt. '),
('landrover', 'Discovery sport', 'Discovery sport.png', 55000, 'grijs', 5, 'diesel', '180', 2015, 'De Land Rover Discovery Sport is een compacte SUV die voor het eerst werd geïntroduceerd in 2015 als opvolger van de Land Rover Freelander.'),
('landrover', 'Defender 90', 'Defender 90.png', 65000, 'wit', 5, 'benzine', '122', 1984, 'De Land Rover Defender 90 is een compacte versie van de iconische Land Rover Defender-serie, die voor het eerst werd geproduceerd in 1984. De Defender 90 werd geproduceerd van 1984 tot 2016 en is zeer gewild vanwege zijn legendarische off-road capaciteiten en robuuste uitstraling. ');
/* mini */
INSERT INTO `cars` (`type`, `model`, `image_url`, `price`, `color`, `amount`, `engine`, `horse_power`, `year_of_release`, `summary`)
VALUES
('mini', 'John Cooper Works', 'jcw.png', 42500, 'zwart', 5, 'benzine', '228', 2008, "De John Cooper Works (JCW) is een reeks van high-performance Mini's die worden geproduceerd door de Britse autofabrikant, Mini. De JCW-modellen zijn ontworpen en gebouwd door de performance afdeling van Mini, die werd opgericht door de legendarische racewagenbouwer, John Cooper."),
('mini', 'Cooper', 'cooper.png', 23000, 'rood', 25, 'benzine', '192', 1961, 'De Mini Cooper is een compacte auto die geproduceerd wordt door de Britse autofabrikant, Mini. Het is een van de meest populaire en iconische modellen van de Mini-lijn.'),
('mini', 'Cooper SD', 'coopersd.png', 41000, 'grijs', 15, 'diesel', '170', 2011, 'De Mini Cooper SD is een sportieve en krachtige variant van de Mini Cooper die wordt geproduceerd door de Britse autofabrikant Mini. Het is ontworpen voor autoliefhebbers die op zoek zijn naar een combinatie van sportiviteit, luxe en efficiëntie.'),
('mini', 'Cooper D', 'cooperd.png', 30000, 'grijs', 12, 'diesel', '116', 2007, 'De Mini Cooper D is een variant van de Mini Cooper die is uitgerust met een diesel motor. Het is ontworpen om een balans te bieden tussen prestaties en brandstofverbruik, wat resulteert in een efficiënte en toch sportieve rijervaring.'),
('mini', 'Cooper S', 'coopers.png', 34000, 'grijs', 12, 'benzine', '178', 2002, 'De Mini Cooper S is een sportieve variant van de Mini Cooper, die meer vermogen, sportieve styling en verbeterde prestaties biedt ten opzichte van de standaard Mini Cooper.'),
('mini', 'Coupe', 'coupe.png', 15000, 'zwart', 8, 'benzine', '122', 2011, 'De Mini Coupe is een tweezits sportcoupé die werd geproduceerd tussen 2011 en 2015.'),
('mini', 'Clubman', 'clubman.png', 32750, 'zwart', 12, 'benzine', '192', 2007, 'De Mini Clubman is een compacte stationwagon die voor het eerst werd geïntroduceerd in 2007.'),
('mini', 'Clubvan', 'clubvan.png', 15750, 'wit', 2, 'benzine', '122', 2012, 'De Mini Clubvan is een kleine bestelwagen op basis van de Mini Clubman. Het model werd voor het eerst geïntroduceerd in 2012 en werd tot 2014 geproduceerd. Het is ontworpen voor klanten die op zoek zijn naar een kleine bedrijfswagen die opvallend, stijlvol en praktisch is.'),
('mini', 'Countryman', 'countryman.png',45000 , 'zilver', 6, 'benzine', '136', 2010, 'De Mini Countryman is een compacte crossover SUV die voor het eerst werd geïntroduceerd in 2010'),
('mini', 'Convertible', 'convertible.png', 35000, 'geel', 5, 'benzine', '136', 2004, 'De Mini Convertible is een cabrioletversie van de Mini en is verkrijgbaar in verschillende uitvoeringen.'),
('mini', 'One', 'one.png', 26000, 'wit', 5, 'benzine', '102', 2001, 'De Mini One is een instapmodel van de Mini-reeks van het Britse automerk Mini. Het is bedoeld als een betaalbaardere optie ten opzichte van andere modellen in de Mini-reeks en wordt vaak gekozen door mensen die geïnteresseerd zijn in de kenmerkende Mini-stijl en -prestaties, maar die niet bereid zijn om de hogere prijzen van andere modellen te betalen.'),
('mini', 'One D', 'oned.png', 24500, 'zwart', 4, 'diesel', '95', 2014, 'De Mini One D is een dieselvariant van de Mini One en wordt aangedreven door een 1,5-liter driecilindermotor met een vermogen van ongeveer 95 pk en een koppel van 220 Nm. Het is een efficiënte en zuinige motor die de auto in ongeveer 11 seconden van 0 naar 100 km/u kan versnellen, met een topsnelheid van ongeveer 190 km/u. De Mini One D is ook uitgerust met een start-stop-systeem en een energieterugwinningssysteem om het brandstofverbruik te optimaliseren en de uitstoot van schadelijke stoffen te verminderen.'),
('mini', 'Seven', 'seven.png', 26000, 'rood', 5, 'benzine', '102', 2015, 'De Mini Seven is een speciale editie van de Mini die in 2015 werd geïntroduceerd ter gelegenheid van de 60e verjaardag van de oorspronkelijke Mini. Het is verkrijgbaar als een driedeurs hatchback of een cabriolet en heeft een aantal unieke kenmerken, waaronder exclusieve lakkleuren, speciale 17-inch velgen en een interieur met Seven-badges op de stoelen en vloermatten.'),
('mini', 'Paceman', 'paceman.png', 35899, 'grijs', 7, 'diesel', '121', 2012, 'De Mini Paceman is een crossover SUV die werd geproduceerd van 2012 tot 2016. Het voertuig is ontworpen als een tweedeurs variant van de Mini Countryman. Het design is geïnspireerd op het concept van de Mini Coupé.'),
('mini', 'Roadster', 'roadster.png', 15750, 'zwart', 8, 'benzine', '122', 2012, 'De Mini Roadster is een tweezits cabriolet die in 2012 werd geïntroduceerd als onderdeel van de tweede generatie van de Mini-modellenreeks. De Roadster was gebaseerd op de Mini Coupé en deelde veel van zijn kenmerken, waaronder de motoren, de transmissies en het onderstel. De productie van de Roadster begon in januari 2012 en eindigde in februari 2015.'),
('mini', 'Electric', 'electric.png', 37469, 'wit', 12, 'elektrisch', '184', 2020, 'De Mini Electric, ook bekend als de Mini Cooper SE, is een volledig elektrische auto van Mini. Het voertuig heeft een elektromotor met een vermogen van 184 pk en een koppel van 270 Nm. Het heeft een actieradius van ongeveer 234 kilometer op een volledig opgeladen batterij. De Mini Electric heeft een acceleratie van 0-100 km/u in 7,3 seconden en heeft een topsnelheid van 150 km/u.');
/* BALLS BALLS */